use crate::models::diff_line::{DiffResult, LineStatus};

/// Export diff result as an HTML file
pub fn export_html(diff_result: &DiffResult, left_title: &str, right_title: &str) -> String {
    let mut html = String::new();

    html.push_str("<!DOCTYPE html>\n<html>\n<head>\n");
    html.push_str("<meta charset=\"utf-8\">\n");
    html.push_str("<title>WinXMerge - Diff Report</title>\n");
    html.push_str("<style>\n");
    html.push_str(CSS);
    html.push_str("</style>\n");
    html.push_str("</head>\n<body>\n");

    // Header
    html.push_str("<div class=\"header\">\n");
    html.push_str("<h1>WinXMerge - Diff Report</h1>\n");
    html.push_str(&format!(
        "<p class=\"summary\">{} differences found</p>\n",
        diff_result.diff_count
    ));
    html.push_str("</div>\n");

    // Table
    html.push_str("<table>\n<thead>\n<tr>\n");
    html.push_str(&format!(
        "<th class=\"line-no\">#</th><th class=\"content\">{}</th>\n",
        escape_html(left_title)
    ));
    html.push_str(&format!(
        "<th class=\"line-no\">#</th><th class=\"content\">{}</th>\n",
        escape_html(right_title)
    ));
    html.push_str("</tr>\n</thead>\n<tbody>\n");

    for line in &diff_result.lines {
        let class = match line.status {
            LineStatus::Equal => "",
            LineStatus::Added => "added",
            LineStatus::Removed => "removed",
            LineStatus::Modified => "modified",
            LineStatus::Moved => "moved",
        };

        html.push_str(&format!("<tr class=\"{}\">\n", class));

        // Left side
        html.push_str(&format!(
            "<td class=\"line-no\">{}</td>",
            line.left_line_no.map(|n| n.to_string()).unwrap_or_default()
        ));
        html.push_str(&format!(
            "<td class=\"content\">{}</td>\n",
            escape_html(&line.left_text)
        ));

        // Right side
        html.push_str(&format!(
            "<td class=\"line-no\">{}</td>",
            line.right_line_no
                .map(|n| n.to_string())
                .unwrap_or_default()
        ));
        html.push_str(&format!(
            "<td class=\"content\">{}</td>\n",
            escape_html(&line.right_text)
        ));

        html.push_str("</tr>\n");
    }

    html.push_str("</tbody>\n</table>\n");
    html.push_str("<div class=\"footer\">Generated by WinXMerge</div>\n");
    html.push_str("</body>\n</html>");

    html
}

/// Export diff result as a unified diff (patch) file
pub fn export_unified_diff(
    diff_result: &DiffResult,
    left_title: &str,
    right_title: &str,
) -> String {
    let mut output = String::new();
    output.push_str(&format!("--- {}\n", left_title));
    output.push_str(&format!("+++ {}\n", right_title));

    // Group consecutive changes into hunks
    let lines = &diff_result.lines;
    if lines.is_empty() {
        return output;
    }

    let context_lines = 3usize;
    let mut i = 0;
    while i < lines.len() {
        // Find the start of a change
        if lines[i].status == LineStatus::Equal {
            i += 1;
            continue;
        }

        // Found a change; build a hunk with context
        let hunk_start = i.saturating_sub(context_lines);
        // Find the end of changes (merging nearby changes)
        let mut hunk_end = i;
        while hunk_end < lines.len() {
            if lines[hunk_end].status != LineStatus::Equal {
                hunk_end += 1;
            } else {
                // Check if another change is within context range
                let lookahead = (hunk_end + context_lines * 2 + 1).min(lines.len());
                let next_change =
                    (hunk_end..lookahead).find(|&j| lines[j].status != LineStatus::Equal);
                if let Some(nc) = next_change {
                    hunk_end = nc + 1;
                } else {
                    break;
                }
            }
        }
        let hunk_end = (hunk_end + context_lines).min(lines.len());

        // Count left/right lines in hunk
        let mut left_count = 0u32;
        let mut right_count = 0u32;
        let mut left_start = 0u32;
        let mut right_start = 0u32;
        let mut left_start_set = false;
        let mut right_start_set = false;

        for line in &lines[hunk_start..hunk_end] {
            if let Some(n) = line.left_line_no {
                if !left_start_set {
                    left_start = n as u32;
                    left_start_set = true;
                }
                left_count += 1;
            }
            if let Some(n) = line.right_line_no {
                if !right_start_set {
                    right_start = n as u32;
                    right_start_set = true;
                }
                right_count += 1;
            }
        }

        if !left_start_set {
            left_start = 1;
        }
        if !right_start_set {
            right_start = 1;
        }

        output.push_str(&format!(
            "@@ -{},{} +{},{} @@\n",
            left_start, left_count, right_start, right_count
        ));

        for line in &lines[hunk_start..hunk_end] {
            match line.status {
                LineStatus::Equal => {
                    output.push(' ');
                    output.push_str(&line.left_text);
                    output.push('\n');
                }
                LineStatus::Removed => {
                    output.push('-');
                    output.push_str(&line.left_text);
                    output.push('\n');
                }
                LineStatus::Added => {
                    output.push('+');
                    output.push_str(&line.right_text);
                    output.push('\n');
                }
                LineStatus::Modified | LineStatus::Moved => {
                    if !line.left_text.is_empty() {
                        output.push('-');
                        output.push_str(&line.left_text);
                        output.push('\n');
                    }
                    if !line.right_text.is_empty() {
                        output.push('+');
                        output.push_str(&line.right_text);
                        output.push('\n');
                    }
                }
            }
        }

        i = hunk_end;
    }

    output
}

fn escape_html(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace(' ', "&nbsp;")
        .replace('\t', "&nbsp;&nbsp;&nbsp;&nbsp;")
}

const CSS: &str = r#"
body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    margin: 0; padding: 20px;
    background: #f5f5f5;
}
.header { margin-bottom: 20px; }
.header h1 { margin: 0; font-size: 24px; }
.summary { color: #666; margin: 4px 0; }
table {
    width: 100%; border-collapse: collapse;
    font-family: "SF Mono", "Menlo", "Monaco", monospace;
    font-size: 13px; background: white;
    border: 1px solid #ddd;
}
thead { background: #f0f0f0; }
th { padding: 6px 8px; text-align: left; border: 1px solid #ddd; font-weight: 600; }
td { padding: 2px 8px; border: 1px solid #eee; white-space: pre; vertical-align: top; }
.line-no { width: 40px; color: #999; text-align: right; user-select: none; }
.content { min-width: 200px; }
tr.added { background: #e6ffec; }
tr.removed { background: #ffebe9; }
tr.modified { background: #fff8c5; }
tr.moved { background: #e0e8ff; }
.footer { margin-top: 20px; color: #999; font-size: 12px; }
@media print {
    body { background: white; padding: 0; }
    .header h1 { font-size: 16px; }
}
"#;
