use crate::models::diff_line::{DiffLine, DiffResult, LineStatus};

/// Export diff result as an HTML file
pub fn export_html(
    diff_result: &DiffResult,
    left_title: &str,
    right_title: &str,
) -> String {
    let mut html = String::new();

    html.push_str("<!DOCTYPE html>\n<html>\n<head>\n");
    html.push_str("<meta charset=\"utf-8\">\n");
    html.push_str("<title>WinXMerge - Diff Report</title>\n");
    html.push_str("<style>\n");
    html.push_str(CSS);
    html.push_str("</style>\n");
    html.push_str("</head>\n<body>\n");

    // Header
    html.push_str("<div class=\"header\">\n");
    html.push_str("<h1>WinXMerge - Diff Report</h1>\n");
    html.push_str(&format!(
        "<p class=\"summary\">{} differences found</p>\n",
        diff_result.diff_count
    ));
    html.push_str("</div>\n");

    // Table
    html.push_str("<table>\n<thead>\n<tr>\n");
    html.push_str(&format!(
        "<th class=\"line-no\">#</th><th class=\"content\">{}</th>\n",
        escape_html(left_title)
    ));
    html.push_str(&format!(
        "<th class=\"line-no\">#</th><th class=\"content\">{}</th>\n",
        escape_html(right_title)
    ));
    html.push_str("</tr>\n</thead>\n<tbody>\n");

    for line in &diff_result.lines {
        let class = match line.status {
            LineStatus::Equal => "",
            LineStatus::Added => "added",
            LineStatus::Removed => "removed",
            LineStatus::Modified => "modified",
            LineStatus::Moved => "moved",
        };

        html.push_str(&format!("<tr class=\"{}\">\n", class));

        // Left side
        html.push_str(&format!(
            "<td class=\"line-no\">{}</td>",
            line.left_line_no.map(|n| n.to_string()).unwrap_or_default()
        ));
        html.push_str(&format!(
            "<td class=\"content\">{}</td>\n",
            escape_html(&line.left_text)
        ));

        // Right side
        html.push_str(&format!(
            "<td class=\"line-no\">{}</td>",
            line.right_line_no
                .map(|n| n.to_string())
                .unwrap_or_default()
        ));
        html.push_str(&format!(
            "<td class=\"content\">{}</td>\n",
            escape_html(&line.right_text)
        ));

        html.push_str("</tr>\n");
    }

    html.push_str("</tbody>\n</table>\n");
    html.push_str("<div class=\"footer\">Generated by WinXMerge</div>\n");
    html.push_str("</body>\n</html>");

    html
}

fn escape_html(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace(' ', "&nbsp;")
        .replace('\t', "&nbsp;&nbsp;&nbsp;&nbsp;")
}

const CSS: &str = r#"
body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    margin: 0; padding: 20px;
    background: #f5f5f5;
}
.header { margin-bottom: 20px; }
.header h1 { margin: 0; font-size: 24px; }
.summary { color: #666; margin: 4px 0; }
table {
    width: 100%; border-collapse: collapse;
    font-family: "SF Mono", "Menlo", "Monaco", monospace;
    font-size: 13px; background: white;
    border: 1px solid #ddd;
}
thead { background: #f0f0f0; }
th { padding: 6px 8px; text-align: left; border: 1px solid #ddd; font-weight: 600; }
td { padding: 2px 8px; border: 1px solid #eee; white-space: pre; vertical-align: top; }
.line-no { width: 40px; color: #999; text-align: right; user-select: none; }
.content { min-width: 200px; }
tr.added { background: #e6ffec; }
tr.removed { background: #ffebe9; }
tr.modified { background: #fff8c5; }
tr.moved { background: #e0e8ff; }
.footer { margin-top: 20px; color: #999; font-size: 12px; }
@media print {
    body { background: white; padding: 0; }
    .header h1 { font-size: 16px; }
}
"#;
